[Output]
ManifestFormat=json
Seed=1d50185f-381f-40c6-8302-9080795f5a7c

[Content]
WithRecommends=no
Packages=
    # base system
    ?priority(required)
    polkitd
    systemd
    systemd-boot-efi
    systemd-resolved
    systemd-repart
    # login and similar necessities
    libnss-systemd
    libpam-systemd
    # tooling
    ca-certificates
    curl
    dmidecode
    ethtool
    iproute2
    jq
    less
    lsof
    man
    mtr-tiny
    net-tools
    nftables
    openssh-server
    procps
    sshguard
    sudo
    tcpdump
    vim
    xz-utils

# Configure OS to skip any setup prompts. Hostname is left empty on purpose to
# have systemd-networkd pick up the hostname via DHCPv6 (when available).
Hostname=
Keymap=us
Locale=C.UTF-8
Timezone=UTC

# Drop unnecessary files to reduce image size.
RemoveFiles=
    /etc/ssh/ssh_host_*
    /usr/share/doc/*
    /usr/share/info/*
    /usr/share/locale/*
    /var/cache/apt/*
    /var/cache/ldconfig/*
    /var/lib/apt/lists/*
    /var/log/*
    /var/log/journal/*
