# The default is ds=NoCloud (camel-case) which pins the NoCloud data-source. It
# will then check for a seed (SMBIOS, CIDATA disk, ...). If no seed is found it
# falls through to the None data-source which does nothing. If we were to use
# ds=nocloud it would count as a seed for the NoCloud data-source, without any
# other seed to use it would fill in synthetic defaults which we do not want.
[Match]
Profiles=virt

[Content]
KernelCommandLine=ds=NoCloud
