frr version 10.0
frr defaults traditional
log syslog debugging
service integrated-vtysh-config

! Add verbose logging to ease troubleshooting.
debug bgp updates in
debug bgp updates out
debug bgp neighbor-events
debug zebra rib
debug zebra events

hostname __HOSTNAME__

interface lo
  ipv6 address __LOOPBACK_IP__/128
!

ipv6 route __PREFIX__ reject
!

bgp as-path access-list LOCALLY_ORIGINATED permit ^$

ipv6 prefix-list PL_OWN_PREFIXES seq 10 permit __PREFIX__
route-map OWN_PREFIXES permit 10
  match ipv6 address prefix-list PL_OWN_PREFIXES
  match as-path LOCALLY_ORIGINATED
!

route-map ALLOW_ALL permit 10
!

route-map RM_SET_SRC6 permit 10
  set src __LOOPBACK_IP__
!

ipv6 protocol bgp route-map RM_SET_SRC6

router bgp __AS_NUMBER__
  bgp router-id __ROUTER_ID__
  bgp bestpath as-path multipath-relax
  no bgp network import-check
  no bgp default ipv4-unicast

  neighbor FABRIC peer-group
  neighbor FABRIC remote-as external
  neighbor __NIC1__ interface peer-group FABRIC
  neighbor __NIC2__ interface peer-group FABRIC

  address-family ipv6 unicast
    network __PREFIX__
    neighbor FABRIC activate
    neighbor FABRIC route-map ALLOW_ALL in
    neighbor FABRIC route-map OWN_PREFIXES out
  exit-address-family
!
